apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app : my-k8s-application
spec:
  selector:
    matchLabels:
      project: 1
  template:
    metadata:
      labels:
        project: 1
    spec:
      containers:
        - name : 1-web
          image: boxerwba/k8s_lecture
          ports:
            - containerPort: 80
